### ISSUE TITLE
Field Checking first 856u entry box

### ISSUE THREAD

**Issue by talljoy** [bywatersolutions/koha-plugin-ebook-deleter#5]
In the first 856u box, is the tool checking for the existence of a string?  
- This field is required, it cannot be blank

Is it checking for a string of a certain length?  
- probably should set a minimum length expected of 3 to 6 characters???  maybe more?

Is it checking for the existence of spaces?
- spaces are invalid in urls, the tool should reject and warn the user.

**Comment by kylemhall** [comment]
Was able to implement the first two suggestions.
